import Footer from "./components/Footer";
import TopBar from "./components/Topbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-h-screen flex flex-col items-center">
          <TopBar />
          <div className="mt-28">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
